services:
  app:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    env_file: .env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      DB_DATABASE: laravel
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: "docker@localhost"
      MAIL_FROM_NAME: "Docker"
    ports:
      - "8000:8000"
    volumes:
      - media-storage:/app/public/media
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started

  queue-worker:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    entrypoint: php artisan queue:work
    healthcheck:
      test: ["CMD", "bin/healthcheck-queue-worker"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      DB_DATABASE: laravel
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: "docker@localhost"
      MAIL_FROM_NAME: "Docker"
    volumes:
      - media-storage:/app/public/media
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit-data-development:/data
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_ENABLE_CHAOS: 1
    networks:
      - laravel-development

networks:
  laravel-development:

volumes:
  media-storage:
  postgres-data-development:
  mailpit-data-development: