services:
  app:
    build:
      context: .
    env_file: .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./public/media:/app/public/media

  scheduler:
    build:
      context: .
    entrypoint: php artisan schedule:work
    env_file: .env.docker
    volumes:
      - ./public/media:/app/public/media
