services:
  app:
    build:
      context: .
    env_file: .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./public/media:/app/public/media

  scheduler:
    build:
      context: .
    entrypoint: php artisan schedule:work
    healthcheck:
      test: ["CMD", "bin/healthcheck-schedule"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env.docker
    volumes:
      - ./public/media:/app/public/media
