services:
  app:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - media_storage:/app/public/media

  scheduler:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    entrypoint: php artisan schedule:work
    healthcheck:
      test: ["CMD", "bin/healthcheck-schedule"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env
    volumes:
      - media_storage:/app/public/media

volumes:
  media_storage:
